apiVersion: v1
kind: Service
metadata:
  name: aggregator-api-srv
spec:
  type: NodePort
  selector:
    app: aggregatorservice
  ports:
    - name: aggregatorservice
      protocol: TCP
      port: 80
      targetPort: 80
