apiVersion: apps/v1
kind: Deployment
metadata:
  name: postapi-mssql-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postapi-mssql
  template:
    metadata:
      labels:
        app: postapi-mssql
    spec:
      containers:
        - name: postapi-mssql
          image: mcr.microsoft.com/mssql/server:2019-latest
          ports:
            - containerPort: 1433
          env:
          - name: MSSQL_PID
            value: "Express"
          - name: ACCEPT_EULA
            value: "Y"
          - name: SA_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mssql
                key: SA_PASSWORD
          volumeMounts:
          - mountPath: /var/opt/postapi-mssql/data
            name: postapi-mssqldb
      volumes:
      - name: postapi-mssqldb
        persistentVolumeClaim:
          claimName: postapi-mssql-claim
---
apiVersion: v1
kind: Service
metadata:
  name: postapi-mssql-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app: postapi-mssql
  ports:
  - name: postapi-mssql
    protocol: TCP
    port: 1434
    targetPort: 1433
---
apiVersion: v1
kind: Service
metadata:
  name: postapi-mssql-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: postapi-mssql
  ports:
  - protocol: TCP
    port: 1434
    targetPort: 1433