version: '3.4'

services:
  postgresserver:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=pa55w0rd!
      - POSTGRES_USER=sa
      - POSTGRES_DB=Comment
    ports:
      - "5432:5432"
  commentapi:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80